-- rankedstats/migrations/002_seed_rank_tiers.sql
--
-- Ranked Stats — rank_tiers seed data.
--
-- =========================================================================================
-- TODO: CONFIRM WITH USER BEFORE RUNNING
-- =========================================================================================
--
-- STATUS: CONFIRMED by user on 2026-08-24. Inserts are live below. Mapping verified against
-- user-supplied data points (Mythic III = 15, Legendary I = 16) and observed data ceiling of
-- exactly 22 ranks. Do not edit this file without new explicit user confirmation.
--
-- Research derived a high-confidence 1..22 mapping (Fandom Elo-table order) below. It matches
-- both user-supplied data points (Mythic III = 15, Legendary I = 16) and the observed data
-- ceiling of exactly 22. It has NOT been confirmed by the user yet.
--
--   #  | Tier          ||  #  | Tier          ||  #  | Tier
--   ---|----------------||-----|----------------||-----|---------------
--   1  | Bronze I       ||  9  | Gold III       || 17  | Legendary II
--   2  | Bronze II      || 10  | Diamond I      || 18  | Legendary III
--   3  | Bronze III     || 11  | Diamond II     || 19  | Masters I
--   4  | Silver I       || 12  | Diamond III    || 20  | Masters II
--   5  | Silver II      || 13  | Mythic I       || 21  | Masters III
--   6  | Silver III     || 14  | Mythic II      || 22  | Pro
--   7  | Gold I         || 15  | Mythic III     ||     |
--   8  | Gold II        || 16  | Legendary I    ||     |
--
-- HOW TO CONFIRM:
--   1. Show the user the table above (or this file) and ask them to confirm or correct it.
--   2. Once confirmed, uncomment every `insert into rank_tiers (...) values (...)` line below
--      (strip the leading `-- ` from each line) and re-check with:
--        grep -c '^insert into rank_tiers' rankedstats/migrations/002_seed_rank_tiers.sql
--      -> should print 22.
--   3. Paste the resulting file into the Supabase SQL Editor and run it once.
--
-- LADDER HISTORY NOTE:
--   This is the POST-2025-02-25 ladder (22 ranks, Masters split into I/II/III, plus Pro at the
--   top). The PRE-rework ladder had only 19 ranks, with an unsplit single "Masters" tier and no
--   "Pro" tier at all. Do not apply this seed to battlelog data recorded before 2025-02-25 —
--   `rank_value` will not mean the same thing.
--
-- CHEAPEST INDEPENDENT SANITY CHECK:
--   Pull the battlelog for any account known to currently sit in Bronze or Silver. Every ranked
--   battle's `rank_value` for that account should fall in the range 1-9 (Bronze I .. Gold III).
--   If it does not, the mapping above is wrong and must be corrected before uncommenting.
--
-- =========================================================================================

insert into rank_tiers (value, tier_name, tier_level, label) values (1, 'Bronze', 1, 'Bronze I') on conflict (value) do nothing;
insert into rank_tiers (value, tier_name, tier_level, label) values (2, 'Bronze', 2, 'Bronze II') on conflict (value) do nothing;
insert into rank_tiers (value, tier_name, tier_level, label) values (3, 'Bronze', 3, 'Bronze III') on conflict (value) do nothing;
insert into rank_tiers (value, tier_name, tier_level, label) values (4, 'Silver', 1, 'Silver I') on conflict (value) do nothing;
insert into rank_tiers (value, tier_name, tier_level, label) values (5, 'Silver', 2, 'Silver II') on conflict (value) do nothing;
insert into rank_tiers (value, tier_name, tier_level, label) values (6, 'Silver', 3, 'Silver III') on conflict (value) do nothing;
insert into rank_tiers (value, tier_name, tier_level, label) values (7, 'Gold', 1, 'Gold I') on conflict (value) do nothing;
insert into rank_tiers (value, tier_name, tier_level, label) values (8, 'Gold', 2, 'Gold II') on conflict (value) do nothing;
insert into rank_tiers (value, tier_name, tier_level, label) values (9, 'Gold', 3, 'Gold III') on conflict (value) do nothing;
insert into rank_tiers (value, tier_name, tier_level, label) values (10, 'Diamond', 1, 'Diamond I') on conflict (value) do nothing;
insert into rank_tiers (value, tier_name, tier_level, label) values (11, 'Diamond', 2, 'Diamond II') on conflict (value) do nothing;
insert into rank_tiers (value, tier_name, tier_level, label) values (12, 'Diamond', 3, 'Diamond III') on conflict (value) do nothing;
insert into rank_tiers (value, tier_name, tier_level, label) values (13, 'Mythic', 1, 'Mythic I') on conflict (value) do nothing;
insert into rank_tiers (value, tier_name, tier_level, label) values (14, 'Mythic', 2, 'Mythic II') on conflict (value) do nothing;
insert into rank_tiers (value, tier_name, tier_level, label) values (15, 'Mythic', 3, 'Mythic III') on conflict (value) do nothing;
insert into rank_tiers (value, tier_name, tier_level, label) values (16, 'Legendary', 1, 'Legendary I') on conflict (value) do nothing;
insert into rank_tiers (value, tier_name, tier_level, label) values (17, 'Legendary', 2, 'Legendary II') on conflict (value) do nothing;
insert into rank_tiers (value, tier_name, tier_level, label) values (18, 'Legendary', 3, 'Legendary III') on conflict (value) do nothing;
insert into rank_tiers (value, tier_name, tier_level, label) values (19, 'Masters', 1, 'Masters I') on conflict (value) do nothing;
insert into rank_tiers (value, tier_name, tier_level, label) values (20, 'Masters', 2, 'Masters II') on conflict (value) do nothing;
insert into rank_tiers (value, tier_name, tier_level, label) values (21, 'Masters', 3, 'Masters III') on conflict (value) do nothing;
insert into rank_tiers (value, tier_name, tier_level, label) values (22, 'Pro', null, 'Pro') on conflict (value) do nothing;
